# Generated by Django 2.1.2 on 2018-11-18 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=200, unique=True)),
                ('club_info', models.TextField(max_length=20000)),
                ('club_logo', models.ImageField(blank=True, upload_to='media_/club_logo')),
                ('admin', models.ManyToManyField(related_name='club_admin', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProposedClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=200, unique=True)),
                ('club_info', models.TextField(max_length=20000)),
                ('club_logo', models.ImageField(upload_to='media_/club_logo')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.Profile')),
            ],
        ),
    ]
