# Generated by Django 2.1.2 on 2018-11-16 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propose_join', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedclub',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.Profile'),
        ),
    ]
