# Generated by Django 2.1.2 on 2018-11-18 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propose_join', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existingclub',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
